### ISSUE TITLE
NPM Errors Recent Releases ESBUILD

### ISSUE THREAD

**Issue by TransRapid** [arter97/immich-native#23]
Since 1.118 this has been an issue, and no updates have been possible. 

Can't figure out what is happening as nothing else changed environment wise. Not sure if anyone else has this issue. It's limited to this pull as even when esbuild installs fine otherwise outside of this, and globally.

Debian Bookworm, Node 22.10.

```
/media/Vault/Backup/Immich/Immich-1730344440/1.119.1/server$ npm ci
npm warn deprecated glob@8.1.0: Glob versions prior to v9 are no longer supported
npm warn deprecated text-encoding@0.6.4: no longer maintained
npm error code 1
npm error path /media/Vault/Backup/Immich/Immich-1730344440/1.119.1/server/node_modules/esbuild
npm error command failed
npm error command sh -c node install.js
npm error node:internal/child_process:1123
npm error     result.error = new ErrnoException(result.error, 'spawnSync ' + options.file);
npm error                    ^
npm error
npm error <ref *1> Error: spawnSync /media/Vault/Backup/Immich/Immich-1730344440/1.119.1/server/node_modules/esbuild/bin/esbuild EACCES
npm error     at Object.spawnSync (node:internal/child_process:1123:20)
npm error     at spawnSync (node:child_process:874:24)
npm error     at Object.execFileSync (node:child_process:917:15)
npm error     at validateBinaryVersion (/media/Vault/Backup/Immich/Immich-1730344440/1.119.1/server/node_modules/esbuild/install.js:99:28)
npm error     at /media/Vault/Backup/Immich/Immich-1730344440/1.119.1/server/node_modules/esbuild/install.js:283:5 {
npm error   errno: -13,
npm error   code: 'EACCES',
npm error   syscall: 'spawnSync /media/Vault/Backup/Immich/Immich-1730344440/1.119.1/server/node_modules/esbuild/bin/esbuild',
npm error   path: '/media/Vault/Backup/Immich/Immich-1730344440/1.119.1/server/node_modules/esbuild/bin/esbuild',
npm error   spawnargs: [ '--version' ],
npm error   error: [Circular *1],
npm error   status: null,
npm error   signal: null,
npm error   output: null,
npm error   pid: 0,
npm error   stdout: undefined,
npm error   stderr: undefined
npm error }
npm error
npm error Node.js v22.11.0
npm error A complete log of this run can be found in: /home/immich/.npm/_logs/2024-10-31T19_50_16_131Z-debug-0.log
```

**Comment by TransRapid** [comment]
Issue seems to be resolved and permission based. Nothing had changed but a hard drive replacement, and I noticed there was an issue with ACL stuff that was causing some problems. Apparently NPM does not like ACLs.
