### ISSUE TITLE
HEIF support missing

### ISSUE THREAD

**Issue by Arvoreen** [arter97/immich-native#9]
So I set up initially on Debian Bookworm.  This version has an older 'libvips' installation, and when sharps gets installed, it uses its prebuilt binaries, which do not include support for HEIF.  I managed to solve this myself by upgrading to trixie, then modifying the install.sh script to add '--build-from-source' to the npm install command line for sharp.

I suppose other option would be to manually update or install libvips on Bookworm, then use the same change to the install command above.  

This is not really a 'bug report' per-se, but more of a note for anyone else that runs into this problem.

The symptom of this is errors like this in the microservices log file (and missing thumbnails for any photos from an iPhone)

```
[Nest] 14529  - 06/06/2024, 1:38:52 PM   ERROR [ImmichMicroservices] [JobService] Unable to run job handler (thumbnailGeneration/generate-preview): Error: Input file contains unsupported image format
[Nest] 14529  - 06/06/2024, 1:38:52 PM   ERROR [ImmichMicroservices] [JobService] Error: Input file contains unsupported image format
    at Sharp.toFile (/data/app/node_modules/sharp/lib/output.js:89:19)
    at MediaRepository.generateThumbnail (/data/app/dist/repositories/media.repository.js:69:14)
    at MediaService.generateThumbnail (/data/app/dist/services/media.service.js:158:48)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MediaService.handleGeneratePreview (/data/app/dist/services/media.service.js:135:29)
    at async /data/app/dist/services/job.service.js:145:36
    at async Worker.processJob (/data/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/data/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 14529  - 06/06/2024, 1:38:52 PM   ERROR [ImmichMicroservices] [JobService] Object:
{
  "id": "09c08053-2f1c-4650-ae49-7554bf2deaaa"
}
```

**Comment by arter97** [comment]
Thanks for the note.

Is "sharp" the only dependency needed for HEIF? The upstream Docker's base image also builds ImageMagick on its own, I figured it's needed for HEIF or RAW support.

Also, if Trixie's libvips supports HEIF, why is "--build-from-source" needed? Shouldn't it automatically pick up libvips support and use it?

Thanks.

**Comment by LazyFunker** [comment]
I have the same problem. But I can't seem to be able to fix it. I've tried both on trixie and ubuntu 22.04, building my own version of libvips with heif support.
Do you have any pointers of how I can fix this?

**Comment by 4v3ngR** [comment]
It appears that the sharp package request libvips to be installed globally (https://www.libvips.org/).

**Comment by relax-a-bit** [comment]
I have installed the libvips according to server/bin/build-libvips.sh but still lacking for heif support. Do I have to rebuild the installation?

**Comment by TransRapid** [comment]
He says he does not include it for copyright reasons.

**Comment by TransRapid** [comment]
Install libde265 lbx265, then libheif, then webm, then libvips, then in your script, npm install sharp --build-from-source --verbose --foreground-scripts.

**Comment by pes502** [comment]
I got the same problem. I tried to fix it for about 4 hours and nothing changed. I tried upgrading from Bookworm to Trixie, compiled my own libvips with all plugins, and then installed sharp from source, but nothing worked. Videos and other images are fine, but images from my iPhone (.HEIC) are missing thumbnails and also cannot be displayed in the browser (but when I download them from the Immich web UI, I can display them normally).

If anyone has any tips, tricks, or maybe a guide (there's a high possibility I overlooked something), I would be glad.

Thank you.

**Comment by TransRapid** [comment]
What happens when you are in your Immich users shell and type__

```
heif-convert
```

**Comment by pes502** [comment]
Sorry, I accidentally deleted my comment. I finally fixed the problem (now I can try to do a new "clean" run and provide detailed guide how to fix this issue for others - I will add it to this comment)

**Comment by pes502** [comment]
Sorry, I accidentally deleted my comment. I finally fixed the problem (now I can try to do a new "clean" run and provide detailed guide how to fix this issue for others - I will add it to this comment)

EDIT 04.12.2024 // 11:06

1. Install Debian Trixie
2. Install everything from this repo (step by step). With Trixie, you can just install ffmpeg directly (no need Jellyfin version)  `apt install ffmpeg`
4. `apt install libvips-dev` (should be this: https://packages.debian.org/trixie/amd64/libvips-dev/download)
5. `cd /var/lib/immich/app/`
6. `npm uninstall sharp`
7. `npm install nan node-addon-api node-gyp`
8. `npm install sharp --build-from-source --verbose --foreground-scripts`
9. `chown -R immich:immich *`
10. Reboot or restart services

**!!!** When you install a new version of Immich in the future, you will probably need to repeat steps 5-10.

@arter97 
> Thanks for the note.
> 
> Is "sharp" the only dependency needed for HEIF? The upstream Docker's base image also builds ImageMagick on its own, I figured it's needed for HEIF or RAW support.
> 
> Also, if Trixie's libvips supports HEIF, why is "--build-from-source" needed? Shouldn't it automatically pick up libvips support and use it?
> 
> Thanks.

I tried it but it's not working (for me atleast)

**Comment by TransRapid** [comment]
I have done this as well, I compiled libvips myself, but as far as sharp that is the same process. I actually added it to a script that i have as a branch of this. - Not (Yet) Publicly Shared.

**Comment by loeeeee** [comment]
> Also, if Trixie's libvips supports HEIF, why is "--build-from-source" needed? Shouldn't it automatically pick up libvips support and use it?

After some digging in sharp, I found that after one compiled the libvips and installed sharp, one needs to delete something inside node_modules to make sharp use the system library.

Here is my solution copied from [Immich in LXC](https://github.com/loeeeee/immich-in-lxc/blob/main/install.sh)

```bash
# Remove sharp dependency so that it use system library
rm -rf $INSTALL_DIR_app/node_modules/@img/sharp-libvips*
rm -rf $INSTALL_DIR_app/node_modules/@img/sharp-linuxmusl-x64
```

The `$INSTALL_DIR_app` is where the immich app locates.

**Comment by btecu** [comment]
I'm using `Fedora` but to get `HEIF` support I just had to install these packages:

```sh
dnf install libheif-devel libheif-freeworld vips vips-devel vips-heif vips-jxl vips-tools
```

Then:
```sh
cd /var/lib/immich/app
rm -rf node_modules/sharp
npm install node-gyp
npm install sharp
```

No special flag is needed and it will probably also work with the next update.
Perhaps we could modify the `install.sh` script to also install `node-gyp`?

**Comment by TransRapid** [comment]
I had to also remove the sharp folder itself recently. Not sure why NPM is not removing it upon uninstall. 


Here is how I have modified my script.


# Install sharp
cd $APP
npm install node-addon-api
npm install node-gyp
npm install --save node-addon-api node-gyp
#SHARP_FORCE_GLOBAL_LIBVIPS=true npm install sharp --build-from-source --verbose --foreground-scripts --save node-addon-api node-gyp

npm remove sharp
rm -r $APP/node_modules/sharp
npm install cpu-features
npm install buildcheck
SHARP_FORCE_GLOBAL_LIBVIPS=true npm install --build-from-source sharp --force --verbose --foreground-scripts

**Comment by horstt** [comment]
> I had to also remove the sharp folder itself recently. Not sure why NPM is not removing it upon uninstall. Also sometimes you need to then clear the redis db or flush the cache.
> 
> Here is how I have modified my script.
> 
> ```
> # Install sharp
> cd $APP
> npm install --save node-addon-api node-gyp
> 
> npm remove sharp
> rm -r $APP/node_modules/sharp
> npm install cpu-features
> npm install buildcheck
> SHARP_FORCE_GLOBAL_LIBVIPS=true npm install --build-from-source sharp --force --verbose --foreground-scripts
> ```

Tried out your recommendation, for me the script stopped, complaining that the folder wasn't there. Is this fix still working for you? I'll escape this issue and see if it works anyway.

**Comment by horstt** [comment]
> [@horstt](https://github.com/horstt) try replacing this line in the script:
> 
> pnpm install sharp
> 
> With this:
> 
> cd $APP
> pnpm remove sharp
> npm_config_build_from_source=true pnpm add sharp --ignore-scripts=false
> pnpm approve-builds
> 
> After the install runs, `pnpm` will try to run the build script, make sure to press `space` to select and then enter.

Thanks, it builds fine with this change. I just still do not have HEIF/HEIC support :( 
 
I restarted from scratch now, using Debian Trixie, but this build errors out building the machine learning component... The script executes the command 
`+ uv sync --no-install-project --no-install-workspace --extra cpu --no-cache --active --link-mode=copy`
with this result:
```
Resolved 147 packages in 10.62s
      Built antlr4-python3-runtime==4.9.3
      Built easydict==1.11
      Built markupsafe==2.1.3
      Built geventhttpclient==2.3.1
      Built zope-interface==6.1                                                                                                                               x Failed to build `msgpack==1.0.7`
  |-> The build backend returned an error
  `-> Call to `setuptools.build_meta.build_wheel` failed (exit status: 1)
      [stdout]
```

With these details:

```
 building 'msgpack._cmsgpack' extension
      creating build/temp.linux-x86_64-cpython-313/msgpack
      x86_64-linux-gnu-g++ -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O2 -Wall -fPIC -I. -I/tmp/.tmpH0iivD/builds-v0/.tmptVzvwn/include
      -I/usr/include/python3.13 -c msgpack/_cmsgpack.cpp -o build/temp.linux-x86_64-cpython-313/msgpack/_cmsgpack.o
      [stderr]
```

and:

```
 error: command '/usr/bin/x86_64-linux-gnu-g++' failed with exit code 1
      hint: This usually indicates a problem with the package or the build environment.
  help: `msgpack` (v1.0.7) was included because `immich-ml:dev` (v2.2.3) depends on `locust` (v2.39.1) which depends on `msgpack`
```

Could this be the python version that's installed with Debian Trixie?

**Comment by btecu** [comment]
Probably, try replacing the `python3` with `python3.12` in the install script.

**Comment by horstt** [comment]
Thanks for the help, this thing is driving me completely crazy. When I replace python3 with python3.12 it complains that it doesn't know what python 3.12 is. I tried installing python 3.12.12 next to the native 3.13.5 using pyenv, but that fails because I'm installing that as root, not as immich, so user immich just knows about Python 3.13.5. Now following instructions to install pyenv for user imich, which is a pain because user immich isn't allowed to log in. Gah!

**Comment by horstt** [comment]
> [@horstt](https://github.com/horstt) try replacing this line in the script:
> 
> pnpm install sharp
> 
> With this:
> 
> cd $APP
> pnpm remove sharp
> npm_config_build_from_source=true pnpm add sharp --ignore-scripts=false
> pnpm approve-builds
> 
> After the install runs, `pnpm` will try to run the build script, make sure to press `space` to select and then enter.

Cheers! After installing Python 3.12.12 the build has succeeded! Immich loads. However, HEIC images still do not get processed... I have checked and from commandline I can successfully run 'heif-info' and 'heif-convert'. Checked, and sharp doesn't seem to be using the local vips, since that is version 8.16.1, and node reports it's using 8.17.3. 
 
So... This sounds like a stupid question, but as I'm stuck... As you say: 'pnpm' will try to run the build script and then asks a few questions. I press space to select 'sharp' and then press enter. Then it asks y/N. Should I press y or N?

**Comment by Ienien77** [comment]
> So I set up initially on Debian Bookworm. [...]upgrading to trixie, then modifying the install.sh script to add '--build-from-source' to the npm install command line for sharp.

Reading you i regain a bit of hope.
It's been two days that i've been trying to install it on Trixie, can't get past machine learning part.
I have a wall of text in front of me and nothing that i understand ... 
What have you done to make it work ? Do i lack skills ? (probably)
